window.tailwind = window.tailwind || {};
window.tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "surface-bright": "#393939",
              "on-secondary-container": "#00424e",
              "secondary-container": "#03b5d3",
              "secondary-fixed": "#acedff",
              "on-primary-fixed": "#23005c",
              "on-primary-container": "#340080",
              "tertiary-fixed": "#b2f746",
              "error": "#ffb4ab",
              "surface-tint": "#d0bcff",
              "primary-container": "#a078ff",
              "surface-dim": "#131313",
              "inverse-primary": "#6d3bd7",
              "on-secondary": "#003640",
              "outline-variant": "#494454",
              "tertiary-container": "#6ba000",
              "on-tertiary-fixed": "#121f00",
              "on-secondary-fixed-variant": "#004e5c",
              "error-container": "#93000a",
              "surface-container-high": "#2a2a2a",
              "surface": "#131313",
              "surface-container-highest": "#353534",
              "on-error": "#690005",
              "on-tertiary-container": "#1c2f00",
              "on-error-container": "#ffdad6",
              "surface-variant": "#353534",
              "on-primary": "#3c0091",
              "inverse-on-surface": "#313030",
              "tertiary": "#98da27",
              "tertiary-fixed-dim": "#98da27",
              "on-tertiary-fixed-variant": "#334f00",
              "background": "#131313",
              "on-surface": "#e5e2e1",
              "primary-fixed-dim": "#d0bcff",
              "outline": "#958ea0",
              "secondary-fixed-dim": "#4cd7f6",
              "primary-fixed": "#e9ddff",
              "surface-container-lowest": "#0e0e0e",
              "on-tertiary": "#213600",
              "on-surface-variant": "#cbc3d7",
              "on-primary-fixed-variant": "#5516be",
              "on-secondary-fixed": "#001f26",
              "on-background": "#e5e2e1",
              "secondary": "#4cd7f6",
              "primary": "#d0bcff",
              "surface-container-low": "#1c1b1b",
              "inverse-surface": "#e5e2e1",
              "surface-container": "#201f1f"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "spacing": {
              "base": "8px",
              "margin-desktop": "64px",
              "margin-mobile": "20px",
              "container-max": "1280px",
              "gutter": "24px"
      },
      "fontFamily": {
              "label-caps": ["JetBrains Mono"],
              "body-md": ["Inter"],
              "display-lg": ["Montserrat"],
              "display-lg-mobile": ["Montserrat"],
              "body-lg": ["Inter"],
              "headline-md": ["Montserrat"],
              "headline-lg-mobile": ["Montserrat"],
              "headline-lg": ["Montserrat"]
      },
      "fontSize": {
              "label-caps": ["12px", {"lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "600"}],
              "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
              "display-lg": ["72px", {"lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "900"}],
              "display-lg-mobile": ["40px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "900"}],
              "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
              "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "700"}],
              "headline-lg-mobile": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700"}],
              "headline-lg": ["48px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}]
      }
    },
  },
};
