window.tailwind = window.tailwind || {};
window.tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "surface-bright": "#FBF9F6",
              "on-secondary-container": "#FCF9F2",
              "secondary-container": "#5B6E58",
              "secondary-fixed": "#E6EDE3",
              "on-primary-fixed": "#FCF9F2",
              "on-primary-container": "#FCF9F2",
              "tertiary-fixed": "#F8ECD9",
              "error": "#BA1A1A",
              "surface-tint": "#C95D4A",
              "primary-container": "#C95D4A",
              "surface-dim": "#FCF9F2",
              "inverse-primary": "#C95D4A",
              "on-secondary": "#FCF9F2",
              "outline-variant": "#DFD8CC",
              "tertiary-container": "#D99447",
              "on-tertiary-fixed": "#1A1D20",
              "on-secondary-fixed-variant": "#435241",
              "error-container": "#FFDAD6",
              "surface-container-high": "#EBE4D7",
              "surface": "#FCF9F2",
              "surface-container-highest": "#DFD8CC",
              "on-error": "#FCF9F2",
              "on-tertiary-container": "#1A1D20",
              "on-error-container": "#410002",
              "surface-variant": "#F2ECE1",
              "on-primary": "#FCF9F2",
              "inverse-on-surface": "#F2ECE1",
              "tertiary": "#D99447",
              "tertiary-fixed-dim": "#D99447",
              "on-tertiary-fixed-variant": "#6A461E",
              "background": "#FCF9F2",
              "on-surface": "#1A1D20",
              "primary-fixed-dim": "#C95D4A",
              "outline": "#E5DDD0",
              "secondary-fixed-dim": "#5B6E58",
              "primary-fixed": "#F6EAE7",
              "surface-container-lowest": "#FCFAF7",
              "on-tertiary": "#FCF9F2",
              "on-surface-variant": "#4E463A",
              "on-primary-fixed-variant": "#873B2E",
              "on-secondary-fixed": "#FCF9F2",
              "on-background": "#1A1D20",
              "secondary": "#5B6E58",
              "primary": "#C95D4A",
              "surface-container-low": "#F8F4EC",
              "inverse-surface": "#1A1D20",
              "surface-container": "#F2ECE1"
      },
      "borderRadius": {
              "DEFAULT": "0.125rem",
              "lg": "0.25rem",
              "xl": "0.375rem",
              "full": "9999px"
      },
      "spacing": {
              "base": "8px",
              "margin-desktop": "64px",
              "margin-mobile": "20px",
              "container-max": "1280px",
              "gutter": "24px"
      },
      "fontFamily": {
              "label-caps": ["JetBrains Mono", "monospace"],
              "body-md": ["Plus Jakarta Sans", "sans-serif"],
              "display-lg": ["Instrument Serif", "serif"],
              "display-lg-mobile": ["Instrument Serif", "serif"],
              "body-lg": ["Plus Jakarta Sans", "sans-serif"],
              "headline-md": ["Instrument Serif", "serif"],
              "headline-lg-mobile": ["Instrument Serif", "serif"],
              "headline-lg": ["Instrument Serif", "serif"]
      },
      "fontSize": {
              "label-caps": ["11px", {"lineHeight": "1", "letterSpacing": "0.15em", "fontWeight": "600"}],
              "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
              "display-lg": ["80px", {"lineHeight": "1.05", "letterSpacing": "-0.02em", "fontWeight": "400"}],
              "display-lg-mobile": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.01em", "fontWeight": "400"}],
              "body-lg": ["18px", {"lineHeight": "1.7", "fontWeight": "400"}],
              "headline-md": ["28px", {"lineHeight": "1.3", "fontWeight": "400"}],
              "headline-lg-mobile": ["36px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "400"}],
              "headline-lg": ["56px", {"lineHeight": "1.15", "letterSpacing": "-0.02em", "fontWeight": "400"}]
      }
    },
  },
};

